import { useEffect, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import type { AdminCustomerDetails } from '../../../models/AdminManagement'
import { addAdminCustomerNote, adjustAdminCredits, adminErrorMessage, getAdminCustomer, setAdminCustomerStatus } from '../../../services/admin'
import LoadingState from '../../ui/loading-state/LoadingState'
import StatusBadge from '../../ui/status-badge/StatusBadge'
import ConfirmAction from '../../ui/confirm-action/ConfirmAction'
import EmptyState from '../../ui/empty-state/EmptyState'
import { statusLabel } from '../../../utils/status-presentation'
import './Admin.css'

export default function AdminCustomerDetails() {
    const { userId } = useParams(); const id = Number(userId)
    const [data, setData] = useState<AdminCustomerDetails | null>(null); const [error, setError] = useState(''); const [working, setWorking] = useState(false)
    const [note, setNote] = useState(''); const [creditAmount, setCreditAmount] = useState(''); const [creditReason, setCreditReason] = useState('')
    const [confirmStatus, setConfirmStatus] = useState('')
    const load = () => getAdminCustomer(id).then(setData).catch(error => setError(adminErrorMessage(error, 'Could not load this customer.')))
    useEffect(() => {
        let cancelled = false
        void getAdminCustomer(id).then(value => { if (!cancelled) setData(value) })
            .catch(loadError => { if (!cancelled) setError(adminErrorMessage(loadError, 'Could not load this customer.')) })
        return () => { cancelled = true }
    }, [id])
    async function changeStatus(status: string) { setWorking(true); try { setData(await setAdminCustomerStatus(id, status)); setError('') } catch (error) { setError(adminErrorMessage(error, 'Could not update account status.')) } finally { setWorking(false) } }
    async function submitNote(event: FormEvent) { event.preventDefault(); setWorking(true); try { setData(await addAdminCustomerNote(id, note)); setNote('') } catch (error) { setError(adminErrorMessage(error, 'Could not save the note.')) } finally { setWorking(false) } }
    async function submitCredits(event: FormEvent) { event.preventDefault(); setWorking(true); try { await adjustAdminCredits(id, Number(creditAmount), creditReason); setCreditAmount(''); setCreditReason(''); await load() } catch (error) { setError(adminErrorMessage(error, 'Could not adjust credits.')) } finally { setWorking(false) } }
    if (!data) return error ? <p className="error">{error}</p> : <LoadingState label="Loading customer details" />
    return <section className="admin-page"><Link className="back-link" to="/admin/customers">← Customers</Link><header className="admin-heading"><div><span className="eyebrow">Customer #{data.user.id}</span><h1>{data.user.name}</h1><p>{data.user.email}</p></div><StatusBadge status={data.user.status} audience="admin" /></header>{error && <p className="error" role="alert">{error}</p>}
        <div className="admin-detail-grid"><article className="admin-panel"><h2>Account</h2><dl className="admin-dl"><div><dt>Role</dt><dd>{data.user.role}</dd></div><div><dt>Joined</dt><dd>{new Date(data.user.createdAt).toLocaleString()}</dd></div><div><dt>Last login</dt><dd>{data.user.lastLoginAt ? new Date(data.user.lastLoginAt).toLocaleString() : 'Never'}</dd></div><div><dt>Active sessions</dt><dd>{data.activeSessions}</dd></div><div><dt>Credit balance</dt><dd>{data.creditBalance}</dd></div></dl><div className="admin-action-row"><button disabled={working || data.user.status === 'active'} onClick={() => setConfirmStatus('active')}>Enable account</button><button className="danger" disabled={working || data.user.status === 'disabled'} onClick={() => setConfirmStatus('disabled')}>Disable account</button></div></article>
        <article className="admin-panel"><h2>Internal note</h2><form className="admin-stack" onSubmit={submitNote}><textarea value={note} onChange={event => setNote(event.target.value)} minLength={3} maxLength={2000} required /><button disabled={working}>Save note</button></form></article>
        <article className="admin-panel"><h2>Adjust AI credits</h2><form className="admin-stack" onSubmit={submitCredits}><input type="number" value={creditAmount} onChange={event => setCreditAmount(event.target.value)} placeholder="Positive or negative amount" required /><textarea value={creditReason} onChange={event => setCreditReason(event.target.value)} placeholder="Required reason" minLength={3} required /><button disabled={working || Number(creditAmount) === 0}>Record adjustment</button></form></article></div>
        <article className="admin-panel"><h2>Orders</h2>{data.orders.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Date</th><th>Type</th><th>Payment</th><th>Fulfillment</th><th>Total</th></tr></thead><tbody>{data.orders.map(order => <tr key={order.id}><td><Link to={`/admin/orders/${order.id}`}>{order.orderNumber}</Link></td><td>{new Date(order.createdAt).toLocaleString()}</td><td>{order.orderKind === 'ai_custom' ? 'AI custom' : order.orderKind}</td><td><StatusBadge status={order.paymentStatus} audience="admin" /></td><td><StatusBadge status={order.fulfillmentStatus} audience="admin" /></td><td>{order.total.toFixed(2)} {order.currency}</td></tr>)}</tbody></table></div> : <EmptyState title="No orders" message="This customer has not placed an order." />}</article>
        <div className="admin-detail-grid"><article className="admin-panel"><h2>Saved AI designs</h2>{data.designs.length ? data.designs.map(design => <div className="admin-list-row" key={design.id}><strong>#{design.id} · {design.product}</strong><span>{design.phoneModel} · {design.caseType}</span><StatusBadge status={design.status} audience="admin" /><small>{design.prompt}</small></div>) : <p>No saved AI designs.</p>}</article><article className="admin-panel"><h2>Saved addresses</h2>{data.addresses.length ? data.addresses.map(address => <address className="admin-list-row" key={address.id}><strong>{address.recipientName}{address.isDefault ? ' · Default' : ''}</strong><span>{address.line1}{address.line2 ? `, ${address.line2}` : ''}<br />{address.city}{address.state ? `, ${address.state}` : ''} {address.postalCode}<br />{address.countryCode}</span>{address.phone && <small>{address.phone}</small>}</address>) : <p>No saved addresses.</p>}</article><article className="admin-panel"><h2>Admin notes</h2>{data.notes.length ? data.notes.map(entry => <div className="admin-list-row" key={entry.id}><p>{entry.note}</p><small>{entry.admin} · {new Date(entry.createdAt).toLocaleString()}</small></div>) : <p>No internal notes.</p>}</article></div>
        <article className="admin-panel"><h2>Credit ledger</h2>{data.creditTransactions.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Date</th><th>Reason</th><th>Change</th><th>Balance</th><th>Reference</th></tr></thead><tbody>{data.creditTransactions.map(entry => <tr key={entry.id}><td>{new Date(entry.createdAt).toLocaleString()}</td><td>{statusLabel(entry.reason, 'admin')}</td><td>{entry.amount > 0 ? '+' : ''}{entry.amount}</td><td>{entry.balanceAfter}</td><td>{entry.referenceId || '—'}</td></tr>)}</tbody></table></div> : <p>No credit transactions.</p>}</article>
        <article className="admin-panel"><h2>Credit purchases</h2>{data.creditPurchases.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Date</th><th>Package</th><th>Credits</th><th>Amount</th><th>Status</th></tr></thead><tbody>{data.creditPurchases.map(entry => <tr key={entry.id}><td>{new Date(entry.createdAt).toLocaleString()}</td><td>{entry.packageName}</td><td>{entry.credits}</td><td>{entry.price.toFixed(2)} {entry.currency}</td><td><StatusBadge status={entry.status} audience="admin" /></td></tr>)}</tbody></table></div> : <p>No credit purchases.</p>}</article>
        <article className="admin-panel"><h2>Commerce audit</h2>{data.audits.length ? data.audits.map(entry => <div className="admin-list-row" key={entry.id}><strong>{statusLabel(entry.action, 'admin')}</strong>{(entry.statusBefore || entry.statusAfter) && <span>{statusLabel(entry.statusBefore, 'admin')} → {statusLabel(entry.statusAfter, 'admin')}</span>}<small>{new Date(entry.createdAt).toLocaleString()}</small></div>) : <p>No commerce audit events.</p>}</article>
        {confirmStatus && <ConfirmAction title={`${confirmStatus === 'disabled' ? 'Disable' : 'Enable'} this account?`} message={confirmStatus === 'disabled' ? 'The customer will be signed out and unable to authenticate until an admin enables the account.' : 'The customer will be able to sign in again.'} confirmLabel={confirmStatus === 'disabled' ? 'Disable account' : 'Enable account'} tone={confirmStatus === 'disabled' ? 'danger' : 'standard'} working={working} onCancel={() => setConfirmStatus('')} onConfirm={() => { const status = confirmStatus; setConfirmStatus(''); void changeStatus(status) }} />}
    </section>
}
